name: Upload to bunny
 
on:
  workflow_dispatch:
  push:
    branches:
      - main
 
jobs:
  upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.22.3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: get dependencies
        run: npm i

      - name: buld
        run: npm run build

      - name: Deploy to BunnyCDN
        uses: ayeressian/bunnycdn-storage-deploy@v2.2.4
        with:
          source: "dist"
          destination: "www"
          storageZoneName: "${{ secrets.STORAGE_NAME }}"
          storagePassword: "${{ secrets.STORAGE_PASSWORD }}"
          upload: "true"
          remove: "false"
          purgePullZone: "false"

          
